title: Roopa Uma Shiv # your name (or website title) here
logo: "/images/IMG-20191003-WA0004.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Grad Student|MS in Data Analytics Engineering|Northeastern University
  <br><br>
  BTech in Information Technology|University of Kerala 
  <br><br>
  <a href="https://www.linkedin.com/in/roopa-uma-shiv/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-161221404-1 # your Google Analytics tracking ID here
